use CUSTOMER_DB;


DELIMITER $$
CREATE PROCEDURE stor_procedure_func3()
BEGIN
    Select CUST_NAME, GRADE from (SELECT  CUST_NAME, GRADE, (OPENING_AMT + RECEIVE_AMT) AS AMOUNT FROM customer) as T WHERE T.AMOUNT > 10000;
END$$
DELIMITER ;


call stor_procedure_func3;